name: 'fsi_demo'
version: '1.0.0'
profile: 'fsi_demo'

model-paths: ["models"]
target-path: "target"

models:
  fsi_demo:
    staging:
      +materialized: view
      # Uses base TRANSFORMED schema directly
    marts:
      +materialized: table
      # Need custom schema override for ANALYTICS
      +schema: analytics
