fsi_demo:
  outputs:
    dev:
      type: snowflake
      warehouse: TRANSFORMATION_WH_S
      database: FSI_DEMO
      schema: TRANSFORMED
      role: ACCOUNTADMIN
      # For Snowflake native dbt - simplified config
      threads: 1
  target: dev