fsi_demo:
  outputs:
    dev:
      type: snowflake
      warehouse: TRANSFORMATION_WH_S
      database: FSI_DEMO
      schema: TRANSFORMED
      # Use SYSADMIN - most workspace users have this role
      role: SYSADMIN
      account: ""
      user: ""
  target: dev
